USE [master]
GO

/****** Object:  Database [COMMANDE]    Script Date: 18/02/2020 08:15:36 ******/
CREATE DATABASE [COMMANDE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMMANDE', FILENAME = N'D:\SQL\DATA\COMMANDE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COMMANDE_log', FILENAME = N'L:\SQL\COMMANDE_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMMANDE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COMMANDE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [COMMANDE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [COMMANDE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [COMMANDE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [COMMANDE] SET ARITHABORT OFF 
GO

ALTER DATABASE [COMMANDE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [COMMANDE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [COMMANDE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [COMMANDE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [COMMANDE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [COMMANDE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [COMMANDE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [COMMANDE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [COMMANDE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [COMMANDE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [COMMANDE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [COMMANDE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [COMMANDE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [COMMANDE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [COMMANDE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [COMMANDE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [COMMANDE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [COMMANDE] SET RECOVERY FULL 
GO

ALTER DATABASE [COMMANDE] SET  MULTI_USER 
GO

ALTER DATABASE [COMMANDE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [COMMANDE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [COMMANDE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [COMMANDE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [COMMANDE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [COMMANDE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [COMMANDE] SET  READ_WRITE 
GO


USE [COMMANDE]
GO

/****** Object:  Table [dbo].[commande_en_ligne]    Script Date: 18/02/2020 08:15:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[commande_en_ligne](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[commande] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


